import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { MarketEvidenceService } from "../market-evidence/service.js";
import { DiscoveryService } from "../discovery/service.js";
import type { WorkspaceAction, WorkspaceBlocker, WorkspaceDecision, WorkspaceRun, WorkspaceStatus } from "./types.js";
const sha = (v: unknown) => createHash("sha256").update(typeof v === "string" ? v : JSON.stringify(v)).digest("hex");
const exists = async (file: string) => readFile(file).then(() => true).catch(() => false);
const root = (project: string) => path.join(project, "workspace-orchestrator");
const json = async <T>(file: string): Promise<T | undefined> => { try { return JSON.parse(await readFile(file, "utf8")) as T; } catch { return undefined; } };
function render(status: WorkspaceStatus): string { return `# 工作流编排状态\n\n- 项目：${status.project.name}\n- 市场证据：${status.evidence.count}；发现：${status.evidence.discovery}\n- 需求：${status.requirements.length}；版本：${status.releases.length}\n\n## 下一步\n\n${status.next.map(x=>`- ${x.action}：${x.reason}\n  - 命令：\`${x.command}\``).join("\n")||"- 当前无自动可执行步骤。"}\n\n## 阻断项\n\n${status.blockers.map(x=>`- [${x.severity}] ${x.id}：${x.message}`).join("\n")||"- 无"}\n`; }
export class WorkspaceOrchestrator {
  async inspect(projectDirectory: string): Promise<WorkspaceStatus> {
    const project = await json<{projectId?:string;projectName?:string}>(path.join(projectDirectory,"project.json")); if (!project?.projectId) throw new Error("工作空间缺少有效 project.json。");
    const evidenceDirectory=path.join(projectDirectory,"market-evidence"), discoveryDirectory=path.join(projectDirectory,"discovery"); let evidenceCount=0; try { evidenceCount=(await new MarketEvidenceService().load(evidenceDirectory)).evidence.length; } catch {}
    let discovery: WorkspaceStatus["evidence"]["discovery"]="MISSING"; if (await exists(path.join(discoveryDirectory,"discovery-report.json"))) { try { const r=await new DiscoveryService().status(evidenceDirectory,discoveryDirectory); discovery=r.stale?"STALE":r.report.status==="reviewed"?"REVIEWED":"PENDING"; } catch { discovery="STALE"; } }
    const requirements: WorkspaceStatus["requirements"]=[]; try { for (const e of await readdir(path.join(projectDirectory,"requirements"),{withFileTypes:true})) if(e.isDirectory()){const d=path.join(projectDirectory,"requirements",e.name),m=await json<{requirementId?:string}>(path.join(d,"requirement.json")); requirements.push({id:m?.requirementId??e.name,directory:path.relative(projectDirectory,d),stages:{design:await exists(path.join(d,"09-prd.md")),valueChain:await exists(path.join(d,"13-value-chain","requirement-value-chain.json")),prototypeConfirmed:await exists(path.join(d,"08-prototype-confirmation.json"))}});}} catch {}
    const releases: WorkspaceStatus["releases"]=[]; try { for (const e of await readdir(path.join(projectDirectory,"releases"),{withFileTypes:true})) if(e.isDirectory()) {const d=path.join(projectDirectory,"releases",e.name); releases.push({version:e.name.replace(/^v/,""),scope:await exists(path.join(d,"release-scope-decision.json")),objective:await exists(path.join(d,"release-objective.json")),retrospective:await exists(path.join(d,"release-retrospective.json"))});}} catch {}
    const decisions: WorkspaceDecision[]=[]; if(discovery!=="MISSING") decisions.push({id:"DISCOVERY-REVIEW",source:"market-discovery",status:discovery==="REVIEWED"?"CONFIRMED":discovery==="STALE"?"STALE":"PENDING",subject:"问题、机会和价值假设",path:"discovery/discovery-report.json"}); for(const q of requirements){const d=path.join(projectDirectory,q.directory);const platform=await json<{decision?:unknown}>(path.join(d,"00-platform-analysis","platform-decision-confirmation.json"));const solution=await json<{status?:string}>(path.join(d,"02-product-outline","solution-options","solution-decision.json"));const canvas=await json<{status?:string}>(path.join(d,"07-mastergo","mastergo-result.json"));if(platform)decisions.push({id:`PLATFORM-${q.id}`,source:"platform-analysis",status:"CONFIRMED",subject:"平台路径",path:path.relative(projectDirectory,path.join(d,"00-platform-analysis","platform-decision-confirmation.json"))});if(solution)decisions.push({id:`SOLUTION-${q.id}`,source:"solution-options",status:solution.status==="selected"?"CONFIRMED":"PENDING",subject:"实施方案",path:path.relative(projectDirectory,path.join(d,"02-product-outline","solution-options","solution-decision.json"))});if(canvas)decisions.push({id:`CANVAS-${q.id}`,source:"mastergo",status:canvas.status==="PASS"?"CONFIRMED":"PENDING",subject:"真实画布验收",path:path.relative(projectDirectory,path.join(d,"07-mastergo","mastergo-result.json"))});} for(const r of releases) decisions.push({id:`RELEASE-${r.version}-SCOPE`,source:"release",status:r.scope?"CONFIRMED":"PENDING",subject:"版本范围",path:`releases/v${r.version}/release-scope-decision.json`});
    const blockers: WorkspaceBlocker[]=[]; if(!evidenceCount) blockers.push({id:"WS-EVIDENCE-001",severity:"BLOCKER",source:"market-evidence",affected:"项目",message:"尚未登记市场证据。",remediation:"登记脱敏证据后生成发现草稿。",recheckCommand:`pae evidence list --evidence-dir ${evidenceDirectory}`}); if(discovery==="PENDING"||discovery==="STALE") blockers.push({id:"WS-DISCOVERY-001",severity:"BLOCKER",source:"market-discovery",affected:"需求价值链",message:discovery==="STALE"?"市场发现审核已失效。":"市场发现等待产品经理审核。",remediation:"审核或重新生成发现草稿。",recheckCommand:`pae discovery status --evidence-dir ${evidenceDirectory} --discovery-dir ${discoveryDirectory}`}); for(const q of requirements) if(q.stages.design&&!q.stages.valueChain) blockers.push({id:`WS-VALUE-${q.id}`,severity:"WARNING",source:"value-chain",affected:q.id,message:"已设计需求缺少价值链。",remediation:"关联已确认发现项和成功指标。",recheckCommand:`pae value check ${path.join(projectDirectory,q.directory)} --discovery-dir ${discoveryDirectory}`});
    for(const decision of decisions.filter(x=>x.status!=="CONFIRMED")) blockers.push({id:`WS-DECISION-${decision.id}`,severity:"BLOCKER",source:decision.source,affected:decision.subject,message:`等待人工决策：${decision.subject}。`,remediation:"在对应原始流程中完成确认。",recheckCommand:`pae workspace decisions ${projectDirectory}`}); const next: WorkspaceAction[]=[]; if(!evidenceCount) next.push({id:"register-evidence",stage:"market-evidence",action:"登记市场证据",reason:"尚无有效证据。",requiredInputs:["脱敏证据JSON"],command:`pae evidence add <证据JSON> --evidence-dir ${evidenceDirectory}`,requiresHumanConfirmation:false,safeToAutoExecute:false}); else if(discovery==="MISSING") next.push({id:"derive-discovery",stage:"market-discovery",action:"生成发现草稿",reason:"已有证据但尚未生成草稿。",requiredInputs:[],command:`pae discovery derive --evidence-dir ${evidenceDirectory} --discovery-dir ${discoveryDirectory}`,requiresHumanConfirmation:false,safeToAutoExecute:true}); else if(discovery!=="REVIEWED") next.push({id:"review-discovery",stage:"market-discovery",action:"审核发现草稿",reason:"发现项未确认或失效。",requiredInputs:["产品经理决策"],command:`pae discovery review ...`,requiresHumanConfirmation:true,safeToAutoExecute:false}); else next.push({id:"refresh-status",stage:"orchestration",action:"刷新工作空间状态",reason:"当前无可安全推进的跨模块动作。",requiredInputs:[],command:`pae workspace status ${projectDirectory}`,requiresHumanConfirmation:false,safeToAutoExecute:true});
    return {schemaVersion:"2.0",generatedAt:new Date().toISOString(),project:{id:project.projectId,name:project.projectName??project.projectId,directory:projectDirectory},evidence:{count:evidenceCount,discovery},competitor:{present:await exists(path.join(projectDirectory,"product","portfolio","competitor-candidate-backlog.json")),pendingReview:false},requirements,releases,decisions,blockers,next};
  }
  async writeStatus(project:string){const status=await this.inspect(project),d=root(project);await mkdir(d,{recursive:true});const jp=path.join(d,"workspace-status.json"),mp=path.join(d,"workspace-status.md");await Promise.all([writeFile(jp,`${JSON.stringify(status,null,2)}\n`),writeFile(mp,render(status))]);return{status,jsonPath:jp,markdownPath:mp};}
  async writePlan(project:string){const status=await this.inspect(project),d=root(project),plan={schemaVersion:"2.0",generatedAt:new Date().toISOString(),inputFingerprint:sha(status),actions:status.next,blockers:status.blockers};await mkdir(d,{recursive:true});const p=path.join(d,"workspace-plan.json"),m=path.join(d,"workspace-plan.md");await Promise.all([writeFile(p,`${JSON.stringify(plan,null,2)}\n`),writeFile(m,`# 动态执行计划\n\n${status.next.map(x=>`- ${x.action}：${x.reason}\n  - ${x.command}`).join("\n")||"- 无"}\n`)]);return{plan,jsonPath:p,markdownPath:m};}
  async run(project:string,execute=false,confirm=false,runId?:string){const d=path.join(root(project),"history");if(runId){const previous=await json<WorkspaceRun>(path.join(d,`${runId}.json`));if(previous)return previous;}const {status,jsonPath}=await this.writeStatus(project);const action=status.next[0];if(execute&&!confirm) throw new Error("workspace continue 真正执行必须同时提供 --execute --confirm。");let files=[jsonPath],service="workspace-orchestrator",result: "PLANNED"|"COMPLETED"|"PAUSED"=execute?"COMPLETED":"PLANNED",pausedReason:string|undefined;if(execute&&action?.id==="derive-discovery"){const r=await new DiscoveryService().derive(path.join(project,"market-evidence"),path.join(project,"discovery"));files=[jsonPath,r.jsonPath,r.markdownPath];service="discovery-service";}else if(execute&&!action?.safeToAutoExecute){result="PAUSED";pausedReason="下一步需要人工确认或输入。";}const run:WorkspaceRun={schemaVersion:"2.0",id:runId??randomUUID(),startedAt:new Date().toISOString(),inputFingerprint:sha(status),actions:[{id:action?.id??"none",service,files,result}],pausedReason};await mkdir(d,{recursive:true});await writeFile(path.join(d,`${run.id}.json`),`${JSON.stringify(run,null,2)}\n`);return run;}
  async history(project:string){try{return(await readdir(path.join(root(project),"history"))).filter(x=>x.endsWith(".json")).sort();}catch{return[];}}
}
